config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :greetings, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/greetings/index.html.erb
<header>
  <h2>Greeter</h2>
</header>

<main>
  <div data-controller="hello">
    <form action="javascript:void(0);">
      <input type="text" data-target="hello.input">

      <button data-action="click->hello#set_name click->hello#say_hello">
        Say hello!
      </button>
    </form>

    <h1 data-target="hello.output"></h1>
    <h2 data-target="hello.output"></h2>
    <h3 data-target="hello.output"></h3>
    <h4 data-target="hello.output"></h4>
    <h4 data-target="hello.output"></h4>
    <h5 data-target="hello.output"></h5>
  </div>
</main>

<%= link_to "Index", root_path %>

app/views/home/index.html.erb
<header>
  <h1>Stimulus on Rails</h1>
  <p>A Stimulus Sketchbook</p>
</header>

<main>
  <h2>Sketches</h2>

  <%= link_to "Greeter", greetings_path %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stimulus on Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload',
      async: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>